import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        width: "100%",
        height: "100%",
    },
    videoContainer: {
        position: "relative",
        width: "100%",
    },
    videoLayer: {
        position: "relative",
        width: "100%",
        zIndex: 1,
    },
    controlsLayer: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        width: "100%",
        zIndex: 10,
    },
    touchableArea: {
        width: "100%",
        height: "100%",
    },
    videoWrapper: {
        width: "100%",
        height: "100%",
    },
    activityIndicator: {
        position: "absolute",
        left: "50%",
        zIndex: 20,
    },
    replayIconContainer: {
        position: "absolute",
        top: "50%",
        left: "50%",
        zIndex: 20,
        transform: [{ translateX: -15 }, { translateY: -15 }],
    },
    replayIconContainerFS: {
        position: "absolute",
        top: "50%",
        left: "50%",
        zIndex: 20,
        transform: [{ translateX: -15 }, { translateY: -15 }],
    },
    replayIcon: {
        width: 30,
        height: 30,
    },
    fullscreenIcon: {
        width: 20,
        height: 20,
        marginRight: 10,
    },
    exitFullscreenIcon: {
        width: 20,
        height: 20,
    },
    video: {
        width: "100%",
        height: "100%",
    },
    controlButton: {
        position: "absolute",
        top: "50%",
        left: "50%",
        zIndex: 20,
        transform: [{ translateX: -20 }, { translateY: -20 }],
        backgroundColor: "white",
        width: 40,
        height: 40,
        borderRadius: 20,
        overflow: "hidden",
        borderWidth: 0,
        justifyContent: "center",
        alignItems: "center",
    },
    bottomBar: {
        backgroundColor: "rgba(50, 50, 50, 0.7)",
        width: "95%",
        position: "absolute",
        bottom: 10,
        left: "2.5%",
        zIndex: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 5,
        paddingVertical: 5,
        gap: 5,
        borderRadius: 20,
    },
    bottomBarFS: {
        backgroundColor: "rgba(50, 50, 50, 0.7)",
        width: "78%",
        position: "absolute",
        left: "11%",
        bottom: 10,
        height: 40,
        paddingHorizontal: 15,
        zIndex: 20,
        flexDirection: "row",
        gap: 5,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
    },
    sliderFS: {
        flex: 1,
        height: 40,
        marginVertical: 10,
    },
    slider: {
        flex: 1,
        height: 10,
        marginVertical: 10,
    },
    trackStyle: {
        height: 4,
        borderRadius: 2,
    },
    timeText: {
        color: "#fff",
        marginLeft: 14,
        fontSize: 12,
    },
    timeTextFS: {
        color: "#fff",
        marginLeft: 12,
    },
    totalTimeText: {
        color: "#ccc",
        fontSize: 12,
    },
    totalTimeTextFS: {
        color: "#ccc",
    },
}); 